---
title: "Practice Demographics & Performance"
author: "Analytics Report generated by Sentient Psychometrics"
date: "`r format(Sys.time(), '%d %B, %Y')`"
geometry: "left=2cm,right=2cm,top=1.5cm,bottom=1.2cm"
output:
  pdf_document:
    latex_engine: pdflatex
header-includes:
- \usepackage[fontsize=7.8pt]{scrextend}
- \usepackage{color}
- \usepackage{booktabs}
- \usepackage[table]{xcolor}
fontfamily: arev
always_allow_html: yes
params:
Sex_Df: 'NULL'
Sexuality_Df: 'NULL'
Relationship_Df: 'NULL'
Workforce_Df: 'NULL'
Education_Df: 'NULL'
Suburb_Df: 'NULL'
Basic_Dem_Df: 'NULL'
Attendance_Arr_Df: 'NULL'
Attendance_Qual_Df: 'NULL'
Prin_Diagnosis_Df: 'NULL'
Sec_Diagnosis_Df: 'NULL'
Therapy_Df: 'NULL'
Referrer_Df: 'NULL'
Dropout_Df: 'NULL'
Clinical_Dem_Df: 'NULL'
Num_Dem_Df: 'NULL'
Num_Dem_Clin_Df: 'NULL'
Imp_Df: 'NULL'
Sig_Imp_Df: 'NULL'
Global_Improvement_Df: 'NULL'
Global_Sig_Improvement_Df: 'NULL'
Global_Improvement_Dx_Df: 'NULL'
Global_Sig_Improvement_Dx_Df: 'NULL'
Custom_Vars_Df: 'NULL'
Custom_Table: 'NULL'
Custom_Num_Table: 'NULL'
Periods: 'NULL'
---


```{r,echo = FALSE,warning=FALSE,comment = NA, results='asis'}

cat('\n#', "General Demographics", '\n')
cat('\n')


kable(Basic_Dem_Df, booktabs = T, format = "latex") %>% kable_styling(position = "left", full_width = T, latex_options = "striped") %>% row_spec(0, bold = T) %>% group_rows("Sex", 1, nrow(Sex_Df)) %>% group_rows("Sexuality", nrow(Sex_Df) + 1, nrow(Sex_Df) + nrow(Sexuality_Df)) %>% group_rows("Relationship Status", nrow(Sex_Df) + nrow(Sexuality_Df) + 1,  nrow(Sex_Df) + nrow(Sexuality_Df) + nrow(Relationship_Df)) %>% group_rows("Workforce", nrow(Sex_Df) + nrow(Sexuality_Df) + nrow(Relationship_Df) + 1, nrow(Sex_Df) + nrow(Sexuality_Df) + nrow(Relationship_Df) + nrow(Workforce_Df)) %>% group_rows("Education", nrow(Sex_Df) + nrow(Sexuality_Df) + nrow(Relationship_Df) + nrow(Workforce_Df) + 1, nrow(Sex_Df) + nrow(Sexuality_Df) + nrow(Relationship_Df) + nrow(Workforce_Df) + nrow(Education_Df)) %>% group_rows("Suburb", nrow(Sex_Df) + nrow(Sexuality_Df) + nrow(Relationship_Df) + nrow(Workforce_Df) + nrow(Education_Df) + 1, nrow(Sex_Df) + nrow(Sexuality_Df) + nrow(Relationship_Df) + nrow(Workforce_Df) + nrow(Education_Df) + nrow(Suburb_Df)) %>%  kable_styling(latex_options="scale_down")

kable(Num_Dem_Df, booktabs = T, format = "latex") %>% kable_styling(position = "left", full_width = T, latex_options = "striped") %>% row_spec(0, bold = T)  %>%  kable_styling(latex_options="scale_down")

```

\newpage 

```{r,echo = FALSE,warning=FALSE,comment = NA, results='asis'}
cat('\n#', "Clinical Demographics", '\n')
cat('\n')

kable(Clinical_Dem_Df, booktabs = T, format = "latex") %>% kable_styling(position = "left", full_width = T, latex_options = "striped") %>% row_spec(0, bold = T) %>%  group_rows("Principal Diagnosis", 1, nrow(Prin_Diagnosis_Df)) %>% group_rows("Secondary Diagnosis", nrow(Prin_Diagnosis_Df) + 1, nrow(Prin_Diagnosis_Df) + nrow(Sec_Diagnosis_Df)) %>% group_rows("Therapy", nrow(Prin_Diagnosis_Df) + nrow(Sec_Diagnosis_Df) + 1,  nrow(Prin_Diagnosis_Df) + nrow(Sec_Diagnosis_Df) + nrow(Therapy_Df)) %>% group_rows("Referrer", nrow(Prin_Diagnosis_Df) + nrow(Sec_Diagnosis_Df) + nrow(Therapy_Df) + 1, nrow(Prin_Diagnosis_Df) + nrow(Sec_Diagnosis_Df) + nrow(Therapy_Df) + nrow(Referrer_Df)) %>% group_rows("Attendance Arrangement", nrow(Prin_Diagnosis_Df) + nrow(Sec_Diagnosis_Df) + nrow(Therapy_Df) + nrow(Referrer_Df) + 1, nrow(Prin_Diagnosis_Df) + nrow(Sec_Diagnosis_Df) + nrow(Therapy_Df) + nrow(Referrer_Df) + nrow(Attendance_Arr_Df)) %>% group_rows("Attendance Quality", nrow(Prin_Diagnosis_Df) + nrow(Sec_Diagnosis_Df) + nrow(Therapy_Df) + nrow(Referrer_Df) + nrow(Attendance_Arr_Df) + 1, nrow(Prin_Diagnosis_Df) + nrow(Sec_Diagnosis_Df) + nrow(Therapy_Df) + nrow(Referrer_Df) + nrow(Attendance_Arr_Df) + nrow(Attendance_Qual_Df)) %>% group_rows("Early Dropout", nrow(Prin_Diagnosis_Df) + nrow(Sec_Diagnosis_Df) + nrow(Therapy_Df) + nrow(Referrer_Df) + nrow(Attendance_Arr_Df) + nrow(Attendance_Qual_Df) + 1, nrow(Prin_Diagnosis_Df) + nrow(Sec_Diagnosis_Df) + nrow(Therapy_Df) + nrow(Referrer_Df) + nrow(Attendance_Arr_Df) + nrow(Attendance_Qual_Df) + nrow(Dropout_Df)) %>%  kable_styling(latex_options="scale_down")
```

```{r,echo = FALSE,warning=FALSE,comment = NA, results='asis'}

kable(Num_Dem_Clin_Df, booktabs = T, format = "latex") %>% kable_styling(position = "left", full_width = T, latex_options = "striped") %>% row_spec(0, bold = T) %>% kable_styling(latex_options="scale_down")

```

\newpage

```{r,echo = FALSE,warning=FALSE,comment = NA, results='asis'}

if(ncol(Custom_Vars_Df) >= 1) {
  
cat('\n#', "User-Defined Custom Variables", '\n')
cat('\n')
}
```

```{r,echo = FALSE,warning=FALSE,comment = NA, results='asis'}

if(!is.null(Custom_Table)) {

kable(Custom_Table, booktabs = T, format = "latex") %>% kable_styling(position = "left", full_width = T, latex_options = "striped") %>% row_spec(0, bold = T) %>% kable_styling(latex_options="scale_down")
                           }

```


```{r,echo = FALSE,warning=FALSE,comment = NA, results='asis'}

if(!is.null(Custom_Num_Table)) {
   
kable(Custom_Num_Table, booktabs = T, format = "latex") %>% kable_styling(position = "left", full_width = T, latex_options = "striped") %>% row_spec(0, bold = T) %>% kable_styling(latex_options="scale_down")
   
                               } 

```

\newpage

```{r,echo = FALSE,warning=FALSE,comment = NA, results='asis'}

cat('\n#', "Improvements In Scores Across All Outcome Measures", '\n')
cat('\n')


kable(Global_Improvement_Df, booktabs = T, format = "latex") %>% kable_styling(position = "left", full_width = F) %>% row_spec(0, bold = T)  %>% column_spec(1, "10.7cm", bold = T) %>% column_spec(2, "1.4cm") %>% column_spec(3, "4.3cm") 

kable(Global_Sig_Improvement_Df, booktabs = T, format = "latex") %>% kable_styling(position = "left", full_width = F) %>% row_spec(0, bold = T) %>% column_spec(1, "10.7cm", bold = T) %>% column_spec( 2, "1.4cm") %>% column_spec(3, "4.3cm")   

kable(Global_Improvement_Dx_Df, booktabs = T, format = "latex") %>% kable_styling(position = "left", full_width = T, latex_options = "striped") %>% row_spec(0, bold = T) %>% add_header_above(c("Symptom Improvement By Diagnosis:" = 1), bold = T) %>% kable_styling(latex_options="scale_down")

kable(Global_Sig_Improvement_Dx_Df, booktabs = T, format = "latex") %>% kable_styling(position = "left", full_width = T, latex_options = "striped") %>% row_spec(0, bold = T) %>% add_header_above(c("Statistically Significant Symptom Improvement By Diagnosis:" = 1), bold = T) %>% kable_styling(latex_options="scale_down")

```

\newpage 

##Reporting Period
```{r,echo = FALSE,warning=FALSE,comment = NA, results='asis'}


if(!is.null(Periods)) {
  cat(Periods, sep = ", ")
} else if (is.null(Periods)) {
  cat("No reporting period was specified. All cases in the analytics dataset were used.")
}


```
