---
title: "Tampa Scale of Kinesiophobia (TSK) "
author: "Analytics Report generated by Sentient Psychometrics"
date: "`r format(Sys.time(), '%d %B, %Y')`"
geometry: "left=2cm,right=2cm,top=1.5cm,bottom=1.2cm"
output:
  pdf_document:
    latex_engine: pdflatex
header-includes:
- \usepackage[fontsize=7.8pt]{scrextend}
- \usepackage{color}
- \usepackage{booktabs}
- \usepackage[table]{xcolor}
fontfamily: arev
always_allow_html: yes
params:
Imp_Df: 'NULL'
Sig_Imp_Df: 'NULL'
Scale_Report_Df: 'NULL'
Periods: 'NULL'
---


\begingroup\Large

\begin{center} \textbf{Information About The Tampa Scale of Kinesiophobia (TSK)} \end{center} 

#What it Measures: 




#What Higher Scores Mean:




#Scale Quality:




#Scale Structure:



\endgroup

\newpage

```{r, echo = FALSE, warning = FALSE, comment = NA, results = 'asis'}

    #TSK nonsig calculations 
    
    TSK_Imp_Df<-dplyr::select(Imp_Df, contains("TSK.Fullscale"))
    SF_Imp_Df<-dplyr::select(Imp_Df, contains("Somatic.Focus"))
    AA_Imp_Df<- dplyr::select(Imp_Df, contains("Activity.Avoidance"))
    
    TSK_Imp_Df<-as.data.frame(gather(TSK_Imp_Df, "Outcome", "Value") %>% na.omit() %>% count(Outcome,Value) %>% mutate(Percentage = paste0(round(100 * n/sum(n), 0), "%"))) %>% dplyr::filter(Value == "Yes") %>% dplyr::select(-c(Outcome,Value))
    SF_Imp_Df<-as.data.frame(gather(SF_Imp_Df, "Outcome", "Value") %>% na.omit() %>% count(Outcome,Value) %>% mutate(Percentage = paste0(round(100 * n/sum(n), 0), "%"))) %>% dplyr::filter(Value == "Yes") %>% dplyr::select(-c(Outcome,Value))
    AA_Imp_Df<-as.data.frame(gather(AA_Imp_Df, "Outcome", "Value") %>% na.omit() %>% count(Outcome,Value) %>% mutate(Percentage = paste0(round(100 * n/sum(n), 0), "%"))) %>% dplyr::filter(Value == "Yes") %>% dplyr::select(-c(Outcome,Value))
    
    
    #TSK sig calculations
    
    
    TSK_Sig_Imp_Df<-dplyr::select(Sig_Imp_Df, contains("TSK.Fullscale"))
    SF_Sig_Imp_Df<-dplyr::select(Sig_Imp_Df, contains("Somatic.Focus"))
    AA_Sig_Imp_Df<- dplyr::select(Sig_Imp_Df, contains("Activity.Avoidance"))
    
    TSK_Sig_Imp_Df<-as.data.frame(gather(TSK_Sig_Imp_Df, "Outcome", "Value") %>% na.omit() %>% count(Outcome,Value) %>% mutate(Percentage = paste0(round(100 * n/sum(n), 0), "%"))) %>% dplyr::filter(Value == "Yes") %>% dplyr::select(-c(Outcome,Value))
    SF_Sig_Imp_Df<-as.data.frame(gather(SF_Sig_Imp_Df, "Outcome", "Value") %>% na.omit() %>% count(Outcome,Value) %>% mutate(Percentage = paste0(round(100 * n/sum(n), 0), "%"))) %>% dplyr::filter(Value == "Yes") %>% dplyr::select(-c(Outcome,Value))
    AA_Sig_Imp_Df<-as.data.frame(gather(AA_Sig_Imp_Df, "Outcome", "Value") %>% na.omit() %>% count(Outcome,Value) %>% mutate(Percentage = paste0(round(100 * n/sum(n), 0), "%"))) %>% dplyr::filter(Value == "Yes") %>% dplyr::select(-c(Outcome,Value))
    
    Improvement_Type<- c("Improvement", "Statistically Reliable Improvement")
    
    Sig_Null<- data.frame(n = "NA", Percentage = "NA")
    
    
     if(nrow(TSK_Imp_Df) == 1 & nrow(TSK_Sig_Imp_Df) == 1) {
      TSK_Percentages<- rbind(TSK_Imp_Df, TSK_Sig_Imp_Df)
      TSK_Percentages<- cbind(Improvement_Type, TSK_Percentages)
    }  else if(nrow(TSK_Imp_Df) == 1 & nrow(TSK_Sig_Imp_Df) == 0) {
      TSK_Percentages = rbind(TSK_Imp_Df, Sig_Null)
       TSK_Percentages<- cbind(Improvement_Type, TSK_Percentages)
    } else if(nrow(TSK_Imp_Df) == 0) {
      TSK_Percentages<- data.frame(x = c("NA", "NA"), y = c("NA", "NA"))
      TSK_Percentages<- cbind(Improvement_Type, TSK_Percentages)
    }

     names(TSK_Percentages)<- c( "", "Number of Cases Improved", "Percentage of Cases Improved")
    
    
    
    
    if(nrow(SF_Imp_Df) == 1 & nrow(SF_Sig_Imp_Df) == 1) {
      SF_Percentages<- rbind(SF_Imp_Df, SF_Sig_Imp_Df)
      SF_Percentages<- cbind(Improvement_Type, SF_Percentages)
    }  else if(nrow(SF_Imp_Df) == 1 & nrow(SF_Sig_Imp_Df) == 0) {
      SF_Percentages = rbind(SF_Imp_Df, Sig_Null)
       SF_Percentages<- cbind(Improvement_Type, SF_Percentages)
    } else if(nrow(SF_Imp_Df) == 0) {
      SF_Percentages<- data.frame(x = c("NA", "NA"), y = c("NA", "NA"))
      SF_Percentages<- cbind(Improvement_Type, SF_Percentages)
    }

     names(SF_Percentages)<- c( "", "Number of Cases Improved", "Percentage of Cases Improved")
    
    
    
     if(nrow(AA_Imp_Df) == 1 & nrow(AA_Sig_Imp_Df) == 1) {
      AA_Percentages<- rbind(AA_Imp_Df, AA_Sig_Imp_Df)
      AA_Percentages<- cbind(Improvement_Type, AA_Percentages)
    }  else if(nrow(AA_Imp_Df) == 1 & nrow(AA_Sig_Imp_Df) == 0) {
      AA_Percentages = rbind(AA_Imp_Df, Sig_Null)
       AA_Percentages<- cbind(Improvement_Type, AA_Percentages)
    } else if(nrow(AA_Imp_Df) == 0) {
      AA_Percentages<- data.frame(x = c("NA", "NA"), y = c("NA", "NA"))
      AA_Percentages<- cbind(Improvement_Type, AA_Percentages)
    }

     names(AA_Percentages)<- c( "", "Number of Cases Improved", "Percentage of Cases Improved")
    
     
     
    Scale_Names<- c("TSK Total", "Somatic Focus", "Activity Avoidance")
    
    TSK_M_Intake<- Scale_Report_Df %>% select(contains("First.Score")) %>% select(contains("TSK")) %>% summarise_all(funs(round(mean(., na.rm = TRUE), digits = 2))) %>% rename_all(funs(c(Scale_Names)))
    TSK_M_Discharge<- Scale_Report_Df %>% select(contains("Last.Score")) %>% select(contains("TSK")) %>% summarise_all(funs(round(mean(., na.rm = TRUE), digits = 2))) %>% rename_all(funs(c(Scale_Names)))
    TSK_M_Change<- Scale_Report_Df %>% select(contains("Change")) %>% select(contains("TSK")) %>% summarise_all(funs(round(mean(., na.rm = TRUE), digits = 2))) %>% rename_all(funs(c(Scale_Names)))
    TSK_Range<- c("Total Scale" = "0-68", "Somatic Focus" = "0-20", "Activity Avoidance" = "0-24")

    
    TSK_Descriptives<- rbind(TSK_M_Intake, TSK_M_Discharge, TSK_M_Change, TSK_Range)
    Data<- c("Mean Intake Score", "Mean Discharge Score", "Mean Change", "Range of Possible Scores")
    TSK_Descriptives<- cbind(Data, TSK_Descriptives)
  
```

##TSK Total Scale

```{r,echo=FALSE,warning=FALSE,comment=NA,results='asis'}

kable(TSK_Percentages, booktabs = T, format = "latex") %>% kable_styling(position = "left", full_width = T, latex_options = "striped") %>% row_spec(0, bold = T) 
```

```{r,echo=FALSE,warning=FALSE,comment=NA, fig.width = 4, fig.height = 1.9, fig.align='left'}
  
#TSK Graph
    
    TSK_Reformat<- dplyr::select(Scale_Report_Df, Name, TSK.Fullscale.First.Score, TSK.Fullscale.Last.Score)
    TSK_Reformat<- TSK_Reformat %>% rename(Pre = TSK.Fullscale.First.Score, Post = TSK.Fullscale.Last.Score)
    TSK_Reformat<- TSK_Reformat %>% dplyr::filter(complete.cases(Pre, Post))

    TSK_Reformat<- gather(TSK_Reformat, Group, TSK.Total.Score, Pre:Post)
    TSK_Reformat$Group<- factor(TSK_Reformat$Group, levels=unique(TSK_Reformat$Group))
    
    TSK_Plot<- ggplot(data = TSK_Reformat, aes (x = factor(Group), y = TSK.Total.Score, group = Name))
    TSK_Plot<- TSK_Plot + geom_line() + xlab("Time") + ylab("TSK Total") 
    
    TSK_Plot + scale_y_continuous(limits = c(0, 68), breaks = c(0,17,34,51,68)) + scale_x_discrete(expand = c(0.2, 0)) + theme_bw() + theme(panel.background = element_rect("#f1f1f1"), axis.line = element_line(colour = "black"), panel.border = element_rect(colour = "#00004c", fill=NA, size=3)) + theme(axis.text.x =  element_text(size=9, family = "AvantGarde", color = "black", face = "bold"), axis.text.y = element_text(size=9, family = "AvantGarde", color = "black", face = "bold"), axis.title.x = element_text(size=9, family = "AvantGarde", face = "bold"), axis.title.y = element_text(size=9, family = "AvantGarde", face = "bold")) 
```

##Somatic Focus Subscale

```{r,echo=FALSE,warning=FALSE,comment=NA,results='asis'}

kable(SF_Percentages, booktabs = T, format = "latex") %>% kable_styling(position = "left", full_width = T, latex_options = "striped") %>% row_spec(0, bold = T)
```

```{r,echo=FALSE,warning=FALSE,comment=NA, fig.width = 4, fig.height = 1.9, fig.align='left'}
TSK_SF_Reformat<- dplyr::select(Scale_Report_Df, Name, TSK.Somatic.Focus.First.Score, TSK.Somatic.Focus.Last.Score)
    TSK_SF_Reformat<- TSK_SF_Reformat %>% rename(Pre = TSK.Somatic.Focus.First.Score, Post = TSK.Somatic.Focus.Last.Score)
    TSK_SF_Reformat<- TSK_SF_Reformat %>% dplyr::filter(complete.cases(Pre, Post))

    TSK_SF_Reformat<- gather(TSK_SF_Reformat, Group, TSK.Somatic.Focus.Score, Pre:Post)
    TSK_SF_Reformat$Group<- factor(TSK_SF_Reformat$Group, levels=unique(TSK_SF_Reformat$Group))
    
    TSK_SF_Plot<- ggplot(data = TSK_SF_Reformat, aes(x = factor(Group), y = TSK.Somatic.Focus.Score, group = Name))
    TSK_SF_Plot<- TSK_SF_Plot + geom_line() + xlab("Time") + ylab("Somatic Focus") 
    
    TSK_SF_Plot + scale_y_continuous(limits = c(0, 20), breaks = c(0, 5,10,15,20)) + scale_x_discrete(expand = c(0.2, 0)) + theme_bw() + theme(panel.background = element_rect("#f1f1f1"), axis.line = element_line(colour = "black"), panel.border = element_rect(colour = "#00004c", fill=NA, size=3)) + theme(axis.text.x =  element_text(size=9, family = "AvantGarde", color = "black", face = "bold"), axis.text.y = element_text(size=9, family = "AvantGarde", color = "black", face = "bold"), axis.title.x = element_text(size=9, family = "AvantGarde", face = "bold"), axis.title.y = element_text(size=9, family = "AvantGarde", face = "bold")) 
    

```

##Activity Avoidance Subscale 

```{r,echo=FALSE,warning=FALSE,comment=NA,results='asis'}

kable(AA_Percentages, booktabs = T, format = "latex") %>% kable_styling(position = "left", full_width = T, latex_options = "striped") %>% row_spec(0, bold = T)

```

```{r,echo=FALSE,warning=FALSE,comment=NA,results='asis', fig.width = 4, fig.height = 1.9, fig.align='left'}
TSK_AA_Reformat<- dplyr::select(Scale_Report_Df, Name, TSK.Activity.Avoidance.First.Score, TSK.Activity.Avoidance.Last.Score)
    TSK_AA_Reformat<- TSK_AA_Reformat %>% rename(Pre = TSK.Activity.Avoidance.First.Score, Post = TSK.Activity.Avoidance.Last.Score)
    TSK_AA_Reformat<- TSK_AA_Reformat %>% dplyr::filter(complete.cases(Pre, Post))

    TSK_AA_Reformat<- gather(TSK_AA_Reformat, Group, TSK.Activity.Avoidance.Score, Pre:Post)
    TSK_AA_Reformat$Group<- factor(TSK_AA_Reformat$Group, levels=unique(TSK_AA_Reformat$Group))
    
    TSK_AA_Plot<- ggplot(data = TSK_AA_Reformat, aes (x = factor(Group), y = TSK.Activity.Avoidance.Score, group = Name))
    TSK_AA_Plot<- TSK_AA_Plot + geom_line() + xlab("Time") + ylab("Activity Avoidance") 
    
    TSK_AA_Plot + scale_y_continuous(limits = c(0, 24), breaks = c(0,8,16,24)) + scale_x_discrete(expand = c(0.2, 0)) + theme_bw() + theme(panel.background = element_rect("#f1f1f1"), axis.line = element_line(colour = "black"), panel.border = element_rect(colour = "#00004c", fill=NA, size=3)) + theme(axis.text.x =  element_text(size=9, family = "AvantGarde", color = "black", face = "bold"), axis.text.y = element_text(size=9, family = "AvantGarde", color = "black", face = "bold"), axis.title.x = element_text(size=9, family = "AvantGarde", face = "bold"), axis.title.y = element_text(size=9, family = "AvantGarde", face = "bold")) 
```

##Average Change Over Treatment Period

```{r,echo=FALSE,warning=FALSE,comment=NA,results='asis'}

kable(TSK_Descriptives, booktabs = T, format = "latex") %>% kable_styling(position = "left", full_width = T, latex_options = "striped") %>% row_spec(0, bold = T)

```

##Reporting Period
```{r,echo = FALSE,warning=FALSE,comment = NA, results='asis'}


if(!is.null(Periods)) {
  cat(Periods, sep = ", ")
} else if (is.null(Periods)) {
  cat("No reporting period was specified. All cases with complete TSK data were used.")
}


```